---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Istanbul
    volumes:
      - /path/to/radarr/config:/config
      - /path/to/radarr/movies:/movies
      - /path/to/radarr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
