---
# https://hub.docker.com/r/josh5/unmanic
version: '2.4'
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1001
      - PGID=100
    volumes:
      - /path/to/config:/config
      - /path/to/library:/library
      - /path/to/encode_cache:/tmp/unmanic
