---
version: '3'
networks:
  my-net:
    external: true
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    networks:
      my-net:
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=$Password #optional
      - CUSTOM_USER=$User
      - TITLE="Calibre Library"
      # - CLI_ARGS= #optional
    volumes:
      - $ConfigPath/calibre:/config
      - $MyBooks:/config/Books
      - $Libreria:/config/Libreria
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
