services:
  virt-manager:
    image: mber5/virt-manager:latest
    restart: always
    ports:
      - 8185:80
    environment:
      # Set DARK_MODE to true to enable dark mode
      DARK_MODE: true
      # Set HOSTS: "['qemu:///session']" to connect to a user session
      HOSTS: "['qemu:///system','lxc:///system']"
    volumes:
      - "/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock"
      - "/var/lib/libvirt/images:/var/lib/libvirt/images"
    #devices:
    #  - "/dev/kvm:/dev/kvm"
