---
version: "3.8"
# https://community.torproject.org/relay/setup/snowflake/standalone/
services:
    snowflake-proxy:
        network_mode: host
        image: thetorproject/snowflake-proxy:latest
        container_name: snowflake-proxy
        restart: unless-stopped
        #command: [ "-ephemeral-ports-range", "30000:60000" ]
####
#
# There is not much to see, check container log and you will see lines like this:
#   2023/08/09 13:23:00 In the last 1h0m0s, there were 7 connections. Traffic Relayed ↓ 21556 KB, ↑ 2377 KB
#
####
