---
version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks:
      - influxdb2
    volumes:
      - /your/path/to/influxdb2/data:/var/lib/influxdb2
      - /your/path/to/influxdb2/config:/etc/influxdb2
    ports:
      - 8086:8086
networks:
  influxdb2:
    name: influxdb2
    driver: bridge