---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/plexmediaserver-database/Library/Application Support/Plex Media Server/Logs:/plex-logs:ro
      - /path/to/docker/docker-config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
